### ISSUE TITLE
[Bug] Can't use legendary actions when there's multiple legendary creatures

### ISSUE THREAD

**Issue by MarkeyMarke** [Ethck/legendary-training-wheels#11]
When there are multiple legendary creatures in the combat, they can't use legendary actions at the end of each other's turns. They can both use legendary actions at the end of a normal creature's turn, however.

**Comment by Ethck** [comment]
Ah, that was indeed an oversight on my part. Legendary Actions can be used on any other creature's turn, but for some reason in the codebase I explicitly only check for turns that are not creatures with legendary actions. I'll get this fixed in the next update sometime this week.
