### ISSUE TITLE
Empty Dialog opens if no Legendary Creatures are in Combat

### ISSUE THREAD

**Issue by akrigline** [Ethck/legendary-training-wheels#2]
Had this module enabled and started combat without legendary creatures. It was popping open at the end of Characters' turns but the dialog was empty.

I was in-session at the time so didn't look closer but if you have trouble reproducing I can take a look again.

**Comment by Ethck** [comment]
I can reproduce this with exactly the method you've described. I don't know how this slipped through my testing, but I'll get it fixed! Thanks for reporting this.

**Comment by Tetraplasm** [comment]
I'm getting a similar result—combat full of non-legendary creatures, every turn triggers an empty legendary actions popup.

**Comment by Ethck** [comment]
@Tetraplasm was there ever a legendary creature in that combat? If you can, I'd like some step by step instructions to reproduce what you're seeing, because I can not reproduce this on my end.

**Comment by Tetraplasm** [comment]
> @Tetraplasm was there ever a legendary creature in that combat? If you can, I'd like some step by step instructions to reproduce what you're seeing, because I can not reproduce this on my end.

I don't think so. I've been doing combat tests and may have forgotten to end combat between tests and there may have been one in there at some point? There was at least one on the scene at one point. I'll do further tests and then reply back soon.
