### ISSUE TITLE
No longer Substracting Legendary Actions after clicking the window

### ISSUE THREAD

**Issue by garzafd** [Ethck/legendary-training-wheels#3]
I've been told on the Foundry discord that this might be due to the DnD5e 1.2.0 update

**Comment by Ethck** [comment]
I will look into this.

**Comment by Ethck** [comment]
So I've looked into it some more. Legendary Training Wheels has not been subtracting remaining Legendary Actions for actors. The only time LTW works with Legendary Actions is to reset them to max on end of the creature's turn. It looks like D&D v1.2.0 however has changed how the abilities are used, and they now have an ability use dialog that pops up. Have you seen that? I'll continue investigating as well.

**Comment by Ethck** [comment]
Some pictures to clarify. Upon using an ability that is configured to consume Legendary Actions, this prompt should show up: 
![image](https://user-images.githubusercontent.com/44616794/102696279-052a3a80-41e2-11eb-8b39-1fab77a863fc.png)

Make sure that the "Consume Resource" dialog is checked, then submit.

Make sure the abilities that consume Legendary Actions are actually set up to consume resources. This is an example:
![image](https://user-images.githubusercontent.com/44616794/102696302-31de5200-41e2-11eb-84cd-e7c584a89f95.png)

Notice the "Activation Cost" line and the "Resource Consumption" lines. They both must be set to the appropriate values for LTW and D&D 5e's resource consumption to work.

**Comment by garzafd** [comment]
Thank you so much! That seemed to be the issue. I might had unselected the box by accident while using it and it never showed again. I deleted the original creature sheet and made it anew. The box reappeared and now it works like it should.  It's working now. Thank you for doing this and thank you so much for the module!

**Comment by Ethck** [comment]
No problem! Please let me know if you have any suggestions , feature requests, and/or other bugs.
