### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Bogus73** [Ethck/legendary-training-wheels#4]
Hi, cool module.

first: 
I am using token action hud and midi qol, so the legendary creature does not click "saving throw" thus the module doesn't ask for a usage of legendary resistance. Could that be worked into the module?

second: 
it doesn't substract any legendary actions from the pop up window. It stays at 3/3 all the time.

Thanks for your hard work!

**Comment by Ethck** [comment]
Apologies for missing this, I for some reason didn't check this module for a while. I can not seem to replicate the "doesn't subtract any legendary actions from the pop-up window" bug. Please ensure that any action that is supposed to use legendary actions is configured to actually use that resource. Additionally, I can not replicate the bug with legendary resistance(s). Please ensure that the actor in question actually has legendary resistance.
