### ISSUE TITLE
Better compatibility with Token Mold?

### ISSUE THREAD

**Issue by buttonpushertv** [Ethck/legendary-training-wheels#5]
I use Token Mold to prepend an adjective to each non-Actor Linked token I drop onto my scenes. The issue I'm encountering is that LTW seems to be looking for a token/actor called *exactly* "Lair Action" to get triggered. Since Token Mold adds the adjectives to any unlinked token, it breaks LTW.

The simplest fix would be if you could create the token and actor as Linked, so that Token Mold didn't change it's name.

Or if there was another way that you knew of to fix it, I'd love to use this more, but as it is, I have to disable Token Mold before I start any combat with a token with Legendary actions/Lair actions to get it to work. These kind of fights happen infrequently that I just don't remember the careful steps I need to take to make it work, so I just don't use LTW when I feel that it could help me.

Any chance of tweaking this so that it doesn't get broken?

**Comment by Ethck** [comment]
My sincerest apologies, I'm only just now seeing this. I will take a look and find the solution. Your lead seems promising.

**Comment by Ethck** [comment]
I have implemented a fix and will release it in a bit. Thanks for your patience.
