### ISSUE TITLE
[Bug] Foundry 9: Module starts working without enabling

### ISSUE THREAD

**Issue by hafdon** [Ethck/legendary-training-wheels#7]
This is a great module. I noticed that it started working, though, before I'd enabled it (but after downloading in the Setup menu) in the Manage Modules settings. I am using a possibly incompatible version of Foundry, though.

module: `0.2.0` (compatibility risk `0.8.6`)
`Foundry 9, build 242`
`dnd5e 1.5.7`
`Chrome Version 97.0.4692.99 (Official Build) (64-bit)`
`node 14.7.x (current LTS)`

**Comment by Ethck** [comment]
This should NOT be possible for a module to do. Are you sure that it's this module? What in particular do you think is evident of this module running?

**Comment by hafdon** [comment]
Well, this module is pretty hard to miss -- it opens up dialog boxes with the legendary actions you have available each turn.

**Comment by akrigline** [comment]
Is it possible you're using a different module that has similar functionality? The code for a module isn't loaded into Foundry when the module isn't enabled so like @Ethck said, this really shouldn't be possible.
