### ISSUE TITLE
[BUG] - LTW does not show dialogs or toaster messages.

### ISSUE THREAD

**Issue by ghost** [Ethck/legendary-training-wheels#8]
No dialogs or toast messages show as I progress through a combat turn. The following shows in the console:

![image](https://user-images.githubusercontent.com/30846057/151671526-19776b95-4780-401d-92b1-99f7ace82b22.png)

The responsible code appears to be:

![image](https://user-images.githubusercontent.com/30846057/151671555-462be601-19e7-44f0-9375-39db0398aacf.png)

line 95 throws the error since lItems is 'undefined' at that point since 'undefined' was returned from getProperty.

![image](https://user-images.githubusercontent.com/30846057/151671708-cea50f8d-d649-45d9-8b6d-1b62ea4e0af1.png)

In the getProperty function, the value passed in is split and the first value parsed is the string '_token'  The if statement at line 295 evaluates as false and hence immediately returns 'undefined'  If I edit the value of 'key' and remove the leading underscore, the function executes normally and returns the expected value.

I'm on Forge, with Foundry v9.245, D&D 5e 1.5.7. I've pared down the modules to just the LTW module, which is v0.2.0.

I know this is painful detail, but I figure too much information is better than not enough. Hope this helps!

Morgan

**Comment by Ethck** [comment]
"painful detail" makes it exceedingly easy for me to identify the issue, so thank you! I'll look into it.

**Comment by ghost** [comment]
That was my intent. I do this stuff for a living, so I hate crappy bug reports as much as any developer. Let me know if you need anything else (such as a guinea pig for testing).

**Comment by Ethck** [comment]
I'd encourage you to check out the feature/v9update branch which *should* solve these issues. It seems back in v0.8.X the _actor & _token were deprecated, and in V9 they were removed, so it was a simple fix! I'll test locally over the weekend and push out the update by Monday.

**Comment by ghost** [comment]
Excellent! I forked the code and tested it locally and I agree with the solution. It looks good to me so far. Thanks for the quick response! I gotta admit, I've learned more about Javascript programming over the last couple of months than I ever wanted to know. I usually work on C# back end stuff, so this is new to me. Wish I could write modules in C#! I've heard there's a way to do with with web assembly but haven't gotten around to figuring it out yet. Thanks again!

**Comment by ghost** [comment]
How does one go about installing from that branch to Forge?

**Comment by Ethck** [comment]
I don't think you can, but I've tested enough that I will release it.
